version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Prometheus Web UI
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Prometheus configuration file
      - prometheus_data:/prometheus # Persistent data storage

  snmp_exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp_exporter
    ports:
      - "9116:9116" # SNMP Exporter Web UI
    volumes:
      - /etc/snmp_exporter/snmp.yml:/etc/snmp_exporter/snmp.yml # SNMP Exporter configuration file

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports:
      - "9115:9115" # Blackbox Exporter Web UI
    volumes:
      - /etc/blackbox_exporter/blackbox.yml:/etc/blackbox_exporter/blackbox.yml 

volumes:
  prometheus_data: