global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

  external_labels:
      monitor: 'example'

scrape_configs:
  # Prometheus job
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

 # Node Exporter job
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

    # Cisco
  - job_name: 'cisco_router'
    scrape_interval: 5s
    metrics_path: /snmp
    params:
      module: [cisco_router]
    static_configs:
      - targets:
        - 10.2.13.200
        - 10.2.13.210
        - 10.2.13.211
        - 10.2.13.212
        - 10.2.13.213
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.2.13.12:9116 
  
  - job_name: 'blackbox'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [icmp]  # Используем модуль ICMP для ping-проверки
    static_configs:
      - targets:
        - 10.2.13.200
        - 10.2.13.210
        - 10.2.13.211
        - 10.2.13.212
        - 10.2.13.213
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '10.2.13.12:9115'  # Адрес Blackbox exporter

